# Generated by Django 2.1.15 on 2024-03-25 14:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0004_auto_20240325_1406'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('guest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadeddocument',
            name='document_name',
        ),
        migrations.RemoveField(
            model_name='uploadeddocument',
            name='document_type',
        ),
        migrations.RemoveField(
            model_name='uploadeddocument',
            name='upload_file',
        ),
        migrations.RemoveField(
            model_name='uploadeddocument',
            name='user',
        ),
        migrations.AddField(
            model_name='uploadeddocument',
            name='description',
            field=models.CharField(default='No description provided', max_length=255),
        ),
        migrations.AddField(
            model_name='uploadeddocument',
            name='file',
            field=models.FileField(default='default/file.pdf', upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='uploadeddocument',
            name='recipient_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_documents', to='host.Client'),
        ),
        migrations.AddField(
            model_name='uploadeddocument',
            name='recipient_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='uploadeddocument',
            name='sender',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='sent_documents', to='host.Client'),
        ),
    ]
