# Generated by Django 2.1.15 on 2024-03-25 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0002_auto_20240325_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadeddocument',
            name='file_s3_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
