# Generated by Django 2.1.15 on 2024-03-25 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0003_uploadeddocument_file_s3_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadeddocument',
            name='file_s3_url',
            field=models.URLField(blank=True),
        ),
    ]
