# Generated by Django 2.1.15 on 2024-03-25 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0003_auto_20240323_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='creator_id',
            field=models.IntegerField(default=None),
        ),
    ]
