# Generated by Django 2.1.15 on 2024-04-01 18:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('host', '0004_auto_20240325_1406'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadClients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='No description provided', max_length=255)),
                ('file_s3_url', models.URLField(blank=True)),
                ('clients', models.ManyToManyField(related_name='received_files', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_files', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
