# Generated by Django 2.1.15 on 2024-04-02 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0005_uploadclients'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadclients',
            name='file',
            field=models.FileField(default='default/file.pdf', upload_to='uploads/'),
        ),
    ]
