# Generated by Django 2.1.15 on 2024-04-02 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0006_uploadclients_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadclients',
            name='clients',
        ),
    ]
