# Generated by Django 2.1.15 on 2024-04-02 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0007_remove_uploadclients_clients'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadclients',
            name='clients',
            field=models.ManyToManyField(related_name='received_files', to='host.Client'),
        ),
    ]
