# Generated by Django 2.1.15 on 2024-04-02 18:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0008_uploadclients_clients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadclients',
            name='clients',
            field=models.ManyToManyField(related_name='received_files', to=settings.AUTH_USER_MODEL),
        ),
    ]
